config/routes.rb
PracticeProject::Application.routes.draw do
  resources :users
  resources :followings
  resource :session
end

app/models/following.rb
class Following < ActiveRecord::Base
  attr_accessible :followee_id, :user_id

  belongs_to :followee,
        :class_name => "User",
        :foreign_key => :followee_id,
        :primary_key => :id

  belongs_to :follower,
  :class_name => "User",
  :foreign_key => :user_id,
  :primary_key => :id

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :username

  before_validation :generate_token, :on => :create

  has_many :followings,
      :class_name => "Following",
      :foreign_key => :user_id,
      :primary_key => :id

  has_many :followees,
  :through => :followings,
  :source => :followee

  has_many :followings_of_user,
  :class_name => "Following",
  :foreign_key => :followee_id,
  :primary_key => :id

  has_many :followers,
  :through => :followings_of_user,
  :source => :follower

  def generate_token
    self.token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :logged_in

  def current_user
    @current_user = User.find_by_token(session[:session_token])
  end

  def logged_in
    redirect_to new_session_url unless current_user
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController

  def index
    @all_users = User.where("id != ?", current_user.id)
    @current_user = current_user
    followees_ids = current_user.followings.pluck(:followee_id)
    cannot_follow = followees_ids << current_user.id
    @unfollowed = User.where("id NOT IN (?)", cannot_follow)
    @followings = current_user.followings.includes(:followee)

    #@followees = @all_users.select {|user| followees_ids.include?(user.id)}
    # @unfollowed = @all_users - @followees
  end

  def create
    current_user.followings.create!(params[:following])
    redirect_to followings_url
  end

  def destroy
    Following.find(params[:id]).destroy
    redirect_to followings_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :logged_in, :only => [:create, :new]

  def new
    render :new
  end

  def create
    user = User.find_by_username(params[:username])
    puts user
    if user.password == params[:password]
      session[:session_token] = user.token
      redirect_to user_url(user)
    else
      flash[:notice] ||= []
      flash[:notice] << "Login failed"
      redirect_to new_session_url
    end
  end

  def destroy
    session[:session_token] = nil
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authorized, :only => [:show]

  def show
    @user = User.find(params[:id])
  end

  def new
    render :new
  end

  def create
    user = User.create!(params[:user])
    session[:session_token] = user.token
    redirect_to user_url(user)
  end

  def authorized
    unless current_user.id.to_s == params[:id]
      redirect_to user_url(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followings/index.html.erb
<h1>Manage your followings <%= @current_user.name %></h1>

<h3>Users you've NOT followed yet</h3>
<% @unfollowed.each do |user| %>
<form action="<%= followings_url %>" method="post">

	<%= link_to user.name, user_url(user)%>
	<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token%>">
	<input type="hidden" name="following[followee_id]" value="<%= user.id %>">
	<input type="submit" value="Follow">

</form>

<% end %>


<h3>Users you've followed</h3>

<% @followings.each do |following| %>
<form action="<%= following_url(following) %>" method="post">
	<input type="hidden" name="_method" value="delete">
	<%= link_to following.followee.name, user_url(following.followee)%>
	<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token%>">

	<input type="submit" value="Unfollow">
</form>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeProject</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% unless flash[:notice].nil? %>

<% flash[:notice].each do |alert|%>
<%= alert %>
<% end %>

<% end %>

<%= yield %>

<form action="<%=session_url%>" method="post">
	<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token%>">
	<input type="hidden" name="_method" value="delete">
	<input type="submit" value="logout">
</form>

</body>
</html>

app/views/users/new.html.erb
<h1>Create a new user!</h1>

<form action="<%= users_url %>" method="post">
	<input type="hidden" name="authenticity_token"
	value="<%= form_authenticity_token%>">

	<label id="user_name">Name</label>
	<input type="text" name="user[name]" id="user_name" />

	<label id="user_username">Username</label>
	<input type="text" name="user[username]" id="user_username" />

	<label id="user_password">Password</label>
	<input type="password" name="user[password]" id="user_password" />

	<input type="submit" value="Signup!">

</form>

app/views/users/show.html.erb
<h1><%=@user.name%>'s Profile Page</h1>


<h3>Followers</h3>
<% @user.followers.each do |follower| %>

<div>
	<%= link_to follower.name, user_url(follower) %>
</div>

<% end %>

<h3>People you are following</h3>
<% @user.followees.each do |followee| %>

<div>
	<%= link_to followee.name, user_url(followee) %>
</div>

<% end %>